name: "ACME"
configName: ["acme"]
stylesheets: []
breakpoints:
  - width: 400
    name: mobile
  - width: 700
    name: desktop
mockStorefrontAPI: true
links:
  - url: https://google.com
    name: "Google Inc"
storefronts:
  - iframe
  - standalone
  - inline
  - callcentre

