name: "ACME"
configName: ["acme"]
stylesheets: []
breakpoints:
  - width: 400
    name: mobile
  - width: 700
    name: desktop
mockStorefrontAPI: true
types:
  iframe:
    width: "600px"
  standalone: true
  inline: true

